### PR TITLE
Changes to ConsoleGUI and NewUserLogin, as well as adding photos

### PR DESCRIPTION
**Pull request by yifanl27**
- Reformatted the ConsoleGUI and NewUserLogin, so that it creates a nicer looking interface for the user and also includes images as headers (designed by Enid) and is overall more colourful
image
^Example of our new opening page
- Changed NewUserLogin so that the gender is in the form of radio buttons, which reduces the need for written user input and makes it more user-friendly

### CODE REVIEW

**Comment by yifanl27** [comment]
Made this pull request right now so that everyone can be aware of the updates in the GUI, and will be continuing to make similar modifications later

**Comment by yifanl27** [comment]
Also wanted to make this pr so that I can see what the conflicts are and also so everyone else who might make future refactoring can be aware of what happened and what will happen

**Comment by yifanl27** [comment]
Current conflicts are now removed

**Comment by Enidx** [comment]
Looks really good! Sees no conflict, I think you can go ahead and merge yours!

**Comment by DavidM0808** [comment]
Nicely done :), merging.

**Pull request merged**
