### PR TITLE
created GUI for console

### PR DESCRIPTION
**Pull request by Enidx**

### CODE REVIEW

**Comment by Enidx** [comment]
Created a ConsoleForGUI package where I copied the consoles from System package and modified them as I am writing the GUI

**Comment by Enidx** [comment]
The new package ConsoleForGUI contains all the new Console files that works with the current GUI. the old Main and Console in System package is not deleted just in case we ever need to refer to them.

**Comment by Enidx** [comment]
To test what we have now, please run MainGUI.java

**Comment by Winnie1029** [comment]
Looks good!

**Pull request merged**
